spring:
  profiles:
    active: "dev"
    
---
name: This is development environment running with local resources
hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    hbm2ddl:
        auto: none
    show_sql: true
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
    pattern:
        file: '"%d{yyyy-MM-dd HH:mm:ss} - %msg%n"'
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 9001
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost/pinesphere_dev
        username: root
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    profiles: dev
    
---
name: This is Production environment running with production resources
entitymanager:
    packagesToScan: com.pinesphere.*
hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    hbm2ddl:
        auto: none
    show_sql: true
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
    pattern:
        file: '"%d{yyyy-MM-dd HH:mm:ss} - %msg%n"'
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 9001
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: pwd
        url: url
        username: username
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    profiles: prod
